# Generated by Django 3.1.1 on 2020-09-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='permalink',
            new_name='url',
        ),
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(default='asdasd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='subreddit',
            field=models.CharField(default='asdasd', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='text_len',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='sub_id',
            field=models.CharField(max_length=7),
        ),
    ]
