# Generated by Django 3.1.1 on 2020-09-20 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20200919_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='delivered_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
