# Generated by Django 3.1.1 on 2020-09-20 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20200920_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='delivered_date',
            new_name='download_date',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='delivered',
            new_name='downloaded',
        ),
    ]
