# Generated by Django 3.1.1 on 2020-09-20 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_auto_20200920_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='download_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
