# Generated by Django 3.1.1 on 2020-09-21 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_auto_20200920_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='download_date',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='downloaded',
        ),
    ]
