# Generated by Django 3.1.1 on 2020-09-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_auto_20200921_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='dub_text',
            field=models.TextField(blank=True),
        ),
    ]
