# Generated by Django 3.1.1 on 2020-10-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_submission_dub_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='dub_len',
            field=models.IntegerField(default=0),
        ),
    ]
