# Generated by Django 3.1.1 on 2020-10-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_auto_20201001_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='sub_len',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
